name: docker_build_push_acr

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the api and push it to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./azure-container-apps-demo
        tags: |
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:${{ github.sha }}
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:latest
        file: ./azure-container-apps-demo/api/Dockerfile

    - name: Build the app and push it to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./azure-container-apps-demo
        tags: |
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:${{ github.sha }}
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:latest
        file: ./azure-container-apps-demo/app/Dockerfile

    - name: Build the appblazor and push it to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./azure-container-apps-demo
        tags: |
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/appblazor/appblazor:${{ github.sha }}
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/appblazor/appblazor:latest
        file: ./azure-container-apps-demo/appblazor/Dockerfile